# (PART) Configuration {-}

# Configure Environment for Full Profiling Pipeline

## Launch an AWS Virtual Machine

Launch an EC2 node using AMI `cytomining/images/hvm-ssd/cytominer-ubuntu-trusty-14.04-amd64-server-*`, created using https://github.com/broadinstitute/imaging-vms/blob/master/cytominer/ (currently private to Imaging Platform).
Note that the region must be set to `US East (N. Virginia)` (`us-east-1a` or `us-east-1b`).
To use a different region, modify the `vpc` module in the AWS infrastructure setup.

You will need to create an AMI for your own infrastructure because the provisioning includes mounting S3 and EFS, which is account specific.
We recommend using an `m4.xlarge` instance, with a 110Gb EBS volume (roughly, EBS size should be ((number of cores -1) * 30)+20).

Note: Proper configuration is essential to mount the S3 bucket.
The following configuration provides an example, named `imaging_platform` (modifications will be necessary).

  * Launch an ec2 instance on AWS
  * AMI: `cytomining/images/hvm-ssd/cytominer-ubuntu-trusty-14.04-amd64-server-1529668435`
  * Instance Type: m4.xlarge
  * Network: vpc-35149752 - Subnet: Default (imaging platform terraform)
  * IAM role: `s3-imaging-platform-role`
  * Add New Volume (if necessary): `EBS` with 110 GiB
  * No Tags
  * Select Existing Security Group: `SSH_HTTP`
  * Review and Launch
  * `ssh -i <USER>.pem ubuntu@<Public DNS IPv4>`

After starting the instance, ensure that the S3 bucket is mounted on `~/bucket`.
If not, run `sudo mount -a`.

```{block2, type='rmdnote'}
Note that given this configuration in this AMI, EFS can only be mounted from `us-east-1a` or `us-east-1b`.
This can be changed by appropriately editing the EFS configuration via Terraform.
```

Log in to the EC2 instance.

Check available space on the instance

```sh
df -h
```

Ensure that the `Available` column is at least 30Gb x `p`, where `p` is the number of plates you will process in parallel when creating the database backend.
We recommend `p` to be one less than the number of cores (`p` = 3 for `m4.xlarge`, so 60Gb should be available).
If you don't have sufficient space, mount an EBS volume (below).

Enter your AWS credentials

```sh
aws configure
```

The infrastructure is configured with one S3 bucket.
Mount this S3 bucket (if it is not automatically mounted)

```sh
sudo mount -a
```

Check that the bucket was was mounted.
This path should exist:

```sh
ls ~/bucket/projects
```

## Define Environment Variables

These variables will be used throughout the project to tag instances, logs etc so that you know which machines are working on what, which files to operate on, where your logs are, etc.

```sh
PROJECT_NAME=2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad

BATCH_ID=2016_04_01_a549_48hr_batch1

BUCKET=imaging-platform

MAXPROCS=3 # m4.xlarge has 4 cores; this should be # of cores on your instance - 1
```

## Create Directories

```{block2, type='rmdcaution'}
See note above about EFS - that it can only be mounted from us-east-1a or 1b.
```

```sh
mkdir -p ~/efs/${PROJECT_NAME}/workspace/

cd ~/efs/${PROJECT_NAME}/workspace/

mkdir -p log/${BATCH_ID}
```

Create a temp directory which is required when creating the database backed using `cytominer-database` (discussed later).
This is also useful if you decide to run CellProfiler directly on this node – running the Cell Painting analysis pipeline results in large temporary files.

```sh
mkdir ~/ebs_tmp
```

```{block2, type='rmdnote'}
If at this point you realize that the ec2 instance does not have enough space (which you can check using `du -h`), create and attach an EBS volume, and then mount it.
Make sure that the EBS is created in the same region and availability zone as the ec2 instance.
For more information about mounting the EBS see https://devopscube.com/mount-ebs-volume-ec2-instance/.
```

```sh
# check the name of the disk
lsblk

#> NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
#> xvda    202:0    0     8G  0 disk
#> └─xvda1 202:1    0     8G  0 part /
#> xvdba    202:80   0   100G  0 disk

# check if it has a file system
sudo file -s /dev/xvdba
# ...likely not, in which case you get:
#> /dev/xvdf: data

# if no file system, then create it
sudo mkfs -t ext4 /dev/xvdba

# mount it
sudo mount /dev/xvdba /home/ubuntu/ebs_tmp/

# change perm
sudo chmod 777 ~/ebs_tmp/
```
