# (PART) Images to measurements  {-}

# Configure Tools to Process Images

## Download Software

You may need to authenticate your GitHub account to be able to clone these:

(Note that cellpainting_scripts is currently a private repository; contact our team for access)

```sh
cd ~/efs/${PROJECT_NAME}/workspace/
mkdir software
cd software
git clone git@github.com:broadinstitute/cellpainting_scripts.git
git clone git@github.com:broadinstitute/pe2loaddata.git
git clone git@github.com:broadinstitute/cytominer_scripts.git
git clone git@github.com:CellProfiler/Distributed-CellProfiler.git
cd ..
```

To authenticate your GitHub account, follow instructions to setup SSH keys here https://help.github.com/articles/connecting-to-github-with-ssh/.

You can also clone these repos by following the structure below and inputting your OAuth token as necessary.

```sh
git clone https://username@github.com/broadinstitute/cytominer_scripts.git
```

If these repos have already been cloned, `git pull` to make sure they are up to date.

This is the resulting structure of `software` on EFS (one level below `workspace`):
```
└── software
    ├── Distributed-CellProfiler
    ├── cellpainting_scripts
    ├── cytominer_scripts
    └── pe2loaddata
```

## Update some packages

The AWS Virtual Machine has several required packages preinstalled. 
However, the ones listed below need to be updated. 

### cytominer-database

```sh
pyenv shell 3.5.1
pip install --upgrade cytominer-database`
```

## Setup Distributed CellProfiler

```sh
cd ~/efs/${PROJECT_NAME}/workspace/software/Distributed-CellProfiler/

pyenv shell 2.7.12

pip install -r files/requirements.txt

```
